# fly.toml app configuration file generated for elixir-redis on 2024-03-18T00:16:03+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'elixir-redis'
primary_region = 'ams'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'elixir-redis.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
